#数据源连接信息
spring:
  datasource:
    username: music
    password: 789233
    url: jdbc:mysql://47.92.159.44:3306/music?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false #设置时区
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #session失效时间
  session:
    timeout: 86400

   # =======================    redis
  redis:
    host: 47.92.159.44    #Redis服务器地址
    port: 6379            #Redis服务器连接端口
    database: 0           #Redis数据库索引（默认为0）
    timeout: 1800000           #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20    #连接池最大连接数（使用负值表示没有限制）
        max-wait: 1800000       #最大阻塞等待时间(负数表示没限制)
        min-idle: 0       #连接池中的最小空闲连接
        max-idle: 5       #连接池中的最大空闲连接


#  security:
#    user:
#      name: wz
#      password: 123
mybatis-plus:
  type-aliases-package: com.ccut.dachuang.model.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
springfox:
  documentation:
    swagger-ui:
      enabled: true
    swagger:
      v2:
        use-model-v3: true
server:
  servlet:
    context-path: /api


